import { resetDayKey } from './config'

export interface Task {
  id: string
  t: string
  time?: string
  done: boolean
  skipped?: boolean
  // Present when this task was auto-generated by a Recurring Plan rather
  // than typed in by hand. Lets the daily reconciliation tell the two
  // apart: manual tasks persist across days untouched, plan-sourced tasks
  // get regenerated fresh from whatever's currently active.
  planId?: string
}

export interface MoneyItem {
  name: string
  target: number
  current: number
}

export interface SavingsItem {
  name: string
  target: number
  saved: number
  withdrawn: number
}

// Fitness now tracks only weight — "workout N×/week" moved to the Habits
// system so it isn't duplicated logic living in two places.
export interface FitnessState {
  weight: string
  lastWeekWeight: string
}

export interface LinkItem {
  name: string
  url: string
}

// ---------------------------------------------------------------------------
// Device Hub
// ---------------------------------------------------------------------------

export type DeviceType = 'laptop' | 'desktop' | 'phone' | 'tablet' | 'tv' | 'other'
export type PresenceStatus = 'active' | 'idle' | 'away' | 'offline'
export type ManualStatus = 'online' | 'offline' | 'connected'

export interface DeviceConnection {
  toDeviceId: string
  label: string
}

export interface DeviceDoc {
  id: string
  name: string
  type: DeviceType
  capability: 'live' | 'manual'
  createdAt: number

  lastSeen?: number
  activity?: string
  currentApp?: string
  currentProject?: string
  battery?: number

  manualStatus?: ManualStatus

  connections?: DeviceConnection[]
}

// Key used in focusSubtasksByTask for when nothing is currently scheduled.
export const UNSCHEDULED_KEY = 'unscheduled'

// ---------------------------------------------------------------------------
// Recurring Plans
//
// One system, three "kinds" of output:
//  - schedule: timed items ("Mon 10:00 Lecture") — auto-fill Today, drive
//    Current Focus same as any manually-typed timed task.
//  - habit: a target count per week ("Gym 4x/week"), no fixed time — tracked
//    via habitLog rather than injected into Today at all.
//  - routine: an untimed checklist template ("University Day": attend
//    classes, review notes...) applied on matching days — injected into
//    Today alongside schedule items, just without a time.
//
// Occurrences are never materialized in advance — "what's due today" is
// always computed live from the plan's rule against today's date. The only
// thing that persists per-occurrence is whatever Today's task list already
// tracks (done/skipped) for that one day's generated task; nothing else
// needs its own record, which is what makes editing or skipping cheap.
// ---------------------------------------------------------------------------

export type PlanKind = 'schedule' | 'habit' | 'routine'
export type RecurrenceFrequency = 'daily' | 'weekly'
export type RecurrenceEnd = 'never' | 'date' | 'count'

export interface RecurrenceRule {
  frequency: RecurrenceFrequency
  daysOfWeek: number[] // 0=Sun..6=Sat; ignored when frequency is 'daily'
  endType: RecurrenceEnd
  endDate?: string // YYYY-MM-DD, used when endType === 'date'
  endCount?: number // used when endType === 'count'
}

export interface PlanScheduleItem {
  time: string
  label: string
}

export interface PlanStats {
  generated: number
  completed: number
  skipped: number
}

export interface RecurringPlan {
  id: string
  name: string
  kind: PlanKind
  startDate: string
  recurrence: RecurrenceRule
  active: boolean
  createdAt: number
  scheduleByDay?: Record<number, PlanScheduleItem[]>
  habitTargetPerWeek?: number
  routineChecklist?: string[]
  stats?: PlanStats
}

// ---------------------------------------------------------------------------
// History — a lightweight daily snapshot written once per day, at the same
// moment the daily reset fires, capturing what would otherwise be lost
// (tasks completed, weight). Lives in its own Firestore collection, not
// inside DashboardState, since it only ever grows and is read for
// streaks/trends, never rewritten daily.
// ---------------------------------------------------------------------------

export interface HistoryEntry {
  date: string // YYYY-MM-DD
  tasksCompleted: number
  tasksTotal: number
  weight?: string
}

export interface DashboardState {
  hasOnboarded: boolean
  lastReset: string
  lastWeekReset: string
  tasks: Task[]
  focusSubtasksByTask: Record<string, Task[]>
  projects: Task[]
  career: Task[]
  balance: string
  balanceDelta: string
  debts: MoneyItem[]
  savings: SavingsItem[]
  fitness: FitnessState
  habitLog: Record<string, string[]> // habit plan id -> array of YYYY-MM-DD dates marked done
  plansSeeded: boolean
  goals: Task[]
  notes: string[]
  links: LinkItem[]
  quote: string
}

export function mondayOf(d: Date): string {
  const date = new Date(d)
  const day = date.getDay()
  const diff = (day === 0 ? -6 : 1) - day
  date.setDate(date.getDate() + diff)
  date.setHours(0, 0, 0, 0)
  return date.toISOString().slice(0, 10)
}

function newTask(t: string, time?: string): Task {
  const task: Task = { id: crypto.randomUUID(), t, done: false }
  if (time) task.time = time
  return task
}

const seedTasks = [
  newTask('Code for 2 hours', '09:00'),
  newTask('Deep work session', '11:00'),
  newTask('Gym', '17:00'),
  newTask('Wind down / plan tomorrow', '20:30'),
]

export const DEFAULT_STATE: DashboardState = {
  hasOnboarded: false,
  lastReset: resetDayKey(new Date()),
  lastWeekReset: mondayOf(new Date()),
  tasks: seedTasks,
  focusSubtasksByTask: {
    [seedTasks[0].id]: [
      newTask('Set up the project structure'),
      newTask('Build the core feature'),
      newTask('Test it end to end'),
    ],
  },
  projects: [newTask('Example project — rename or delete me'), newTask('Portfolio site')],
  career: [newTask('Update CV & LinkedIn'), newTask('Apply to 1 role this week')],
  balance: '£1,234.56',
  balanceDelta: '↑ +£120 this month',
  debts: [{ name: 'Example debt — rename me', target: 1000, current: 250 }],
  savings: [{ name: 'Example goal — rename me', target: 500, saved: 100, withdrawn: 0 }],
  fitness: {
    weight: '70kg',
    lastWeekWeight: '70.5kg',
  },
  habitLog: {},
  plansSeeded: false,
  goals: [newTask('Example goal — rename or delete me'), newTask('Debt free by December')],
  notes: ['Example note — click to edit, ✕ to delete'],
  links: [
    { name: 'VS Code', url: 'vscode://file/' },
    { name: 'GitHub', url: 'https://github.com' },
    { name: 'Spotify', url: 'https://open.spotify.com' },
  ],
  quote: 'Discipline builds the freedom you want.',
}